links:
  - title: Be Prepared
    description: Protect yourself, family and property from flood events.
    permalink: /be-prepared/

  - title: River and Weather
    description: River gauges, flood and weather resources.
    permalink: /river-and-weather/

  - title: News
    description: News and updates from Upper Nehalem Flood.
    permalink: /news/

  - title: Map
    description: Upper Nehalem interactive flood map.
    permalink: https://sage-meerkat-23394f.netlify.app/

  - title: Projects
    description: Upper Nehalem Flood projects.
    permalink: /projects/
  
  

    # items:
    #   - title: Nehalem River at Clear Creek
    #     permalink: https://water.weather.gov/ahps2/hydrograph.php?wfo=pqr&gage=veno3&prob_type=stage&source=hydrograph
    #   - title: Rock Creek at Vernonia
    #     permalink: https://water.weather.gov/ahps2/hydrograph.php?wfo=pqr&gage=rcbo3&prob_type=stage&source=hydrograph


partners:
  - title: City of Vernonia
    image: /images/partners/Vernonia_City_Banner.png
    href: https://www.vernonia-or.gov

  - title: City of Vernonia
    image: /images/partners/Vernonia_City_Banner.png
    href: https://www.vernonia-or.gov

  - title: City of Vernonia
    image: /images/partners/Vernonia_City_Banner.png
    href: https://www.vernonia-or.gov
